version: '1'
services:
  # Spark master with 3 workers
  # Spark UI is available at http://localhost:8181
  spark:
    container_name: spark
    image: bitnami/spark:3.1.2
    user: root
    hostname: spark
    networks:
      - default_network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_OPTS="-Dspark.deploy.defaultCores=2" # Spark standalone mode supports FIFO scheduler across applications, so we need to specify number of cores per task
    volumes:
      - ../app:/usr/local/spark/app
      - ../resources:/usr/local/spark/resources
    ports:
      - "8181:8080"
      - "7077:7077"
    restart: always

  spark-worker-1:
    container_name: spark-worker-1
    image: bitnami/spark:3.1.2
    user: root
    networks:
      - default_network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G # Worker Memory can be increased or decreased depending on the amount of data you want to process
      - SPARK_WORKER_CORES=4 # Number of cores per worker can also be increased or decreased
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../:/usr/local/spark/app
      - ../resources:/usr/local/spark/resources
    restart: always

  spark-worker-2:
    container_name: spark-worker-2
    image: bitnami/spark:3.1.2
    user: root
    networks:
      - default_network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../:/usr/local/spark/app
      - ../resources:/usr/local/spark/resources
    restart: always

networks:
  default_network:
    name: docker_net
